### PR TITLE
Update docspa-core.component.ts and router.sevice.ts

### PR DESCRIPTION
**Pull request by gnu4cn**
Pass a snapshot is not need.

### CODE REVIEW

**Comment by Hypercubed** [comment]
Can you explain... looks like a required parameter of `RouterService#activateRoute`

**Comment by gnu4cn** [comment]
> Can you explain... looks like a required parameter of `RouterService#activateRoute`

Exactly it's not need to pass a snapshot to the activateRoute method. I've test it. We can get all the information from the route url.

**Comment by Hypercubed** [comment]
That would require rewriting the `activateRoute` method:

```
  activateRoute(snapshot: ActivatedRouteSnapshot) {
    const url = snapshot.url.map(s => s.path).join('/');
    let root = this.router.url;
    if (snapshot.fragment) {
      root = root.replace(new RegExp('#' + snapshot.fragment + '$'), '');
    }
    root = root.replace(new RegExp(url + '$'), '');
    if (!root.endsWith('/')) {
      root += '/';
    }
    const path = url + (snapshot.fragment ? `#${snapshot.fragment}` : '');
    this.go(path, root);
  }
```

**Comment by gnu4cn** [comment]
In another request, I rewrote the method.

**Comment by gnu4cn** [comment]
I should make pull requests together.

**Pull request closed without merging**
